### ISSUE TITLE
Um this is going to sound dumb but I how do I get this to work?

### ISSUE THREAD

**Issue by TylerGames1** [alekxeyuk/Skribbl.io-Bot#2]
If I need the Dependencies do I download it then drag it in to the folder with the bot and stuff?

**Comment by alekxeyuk** [comment]
No, you need to install dependencies using standart python install module called - pip.
Like this
```bash
pip install aiohttp
```

**Comment by TylerGames1** [comment]
I try to install socketio but it says something is wrong with setuptools so I upgrade setup tools and it still says it
