### ISSUE TITLE
"join" parameter doesn't work

### ISSUE THREAD

**Issue by ShiRO777** [alekxeyuk/Skribbl.io-Bot#21]
The join parameter doesn't work, meaning I can't join private games.

**Comment by ShiRO777** [comment]
Fixed, head to line 30 and replace the code with

`await sio.connect(f"wss://skribbl.io:{SETTINGS['port']}/{SETTINGS['join']}")`

**Comment by ShiRO777** [comment]
Note, skribbl.io uses 3 different ports for private games, 5001, 5002, 5003, usually its 5002 or 5001; I would make a .bat that does both and then close the one that doesn't work.

**Comment by GrimReaperFloof** [comment]
You mean line 254. Just gonna say it so further confusion won't happen.

**Comment by ar065** [comment]
This no longer works...
